### PR TITLE
[T4242] Fix version control and commenting feature bug

### PR DESCRIPTION
**Pull request by UndefinedZZK**
We migrated from bower to npm, but in angular-rich-text-diff we didn't updated one of its dependency (google-diff-match-patch) correctly. We did use an alternative npm package, however we didn't import in the code. So this change just import it into the package, and should fix the bug as discribed in ticket.

### CODE REVIEW

**Review by timgl — APPROVED** [review]

**Review by MrSaints — CHANGES_REQUESTED** [review]
I believe `angular-rich-text-diff.js` is just an artefact of some transpilation from the TypeScript version. If that's the case, perhaps we should be modifying the TS source instead. But that's just my view...

**Comment by timgl** [comment]
Good point @MrSaints .

When those changes are made, we can safely merge as we have Kvasir pointing at a specific commit.

**Comment by UndefinedZZK** [comment]
@MrSaints Well after a few minutes of researching, I noticed that if I want to recompile those ts files, then I need use bower to get all dependencies (mainly for bower_components/dt-angular/angular.d.ts). But as you know we are not using bower anymore. So not quite sure what to do, should I use bower to do that locally and then commit it, or just remove ts files as we are not using it?

**Comment by MrSaints** [comment]
@UndefinedZZK You can decide.

**Review by MrSaints — APPROVED** [review]

**Comment by wcs-arachnys** [comment]
QA'd and approved to merge; see phabricator for details

**Pull request merged**
